version: '3'
services:
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: admin
  web:
    build: .
    ports:
    - "80:7777"
    depends_on: postgres
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]